# Generated by Django 4.0.6 on 2022-07-18 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_alter_city_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='language',
            name='slug',
        ),
    ]
